
"""init schema

Revision ID: ea724f50b0a2
Revises:
Create Date: 2026-02-02 10:00:00
"""


from alembic import op
import sqlalchemy as sa

revision = 'ea724f50b0a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dsl_version', sa.String(length=16), nullable=False),
    sa.Column('dsl_hash', sa.String(length=64), nullable=False),
    sa.Column('dsl_payload', sa.JSON(), nullable=False),
    sa.Column('design_system_version', sa.String(length=32), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animations_dsl_hash'), 'animations', ['dsl_hash'], unique=False)
    op.create_index(op.f('ix_animations_uuid'), 'animations', ['uuid'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animation_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['animation_id'], ['animations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qc_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animation_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['animation_id'], ['animations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('renderer_version', sa.String(length=32), nullable=False),
    sa.Column('output_path', sa.Text(), nullable=False),
    sa.Column('render_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['animation_id'], ['animations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('renders')
    op.drop_table('qc_decisions')
    op.drop_table('ideas')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_animations_uuid'), table_name='animations')
    op.drop_index(op.f('ix_animations_dsl_hash'), table_name='animations')
    op.drop_table('animations')
    # ### end Alembic commands ###
